const Homeproduct = [
  {
    id: 1,
    Name: "product1",
    price: "26",
    image: "image/p1.webp",
    cat: "tv",
    type: "new",
  },
  {
    id: 2,
    Name: "product2",
    price: "96",
    image: "image/p2.webp",
    cat: "laptop",
    type: "new",
  },
  {
    id: 3,
    Name: "product3",
    price: "236",
    image: "image/p3.webp",
    cat: "watch",
    type: "new",
  },
  {
    id: 4,
    Name: "product4",
    price: "636",
    image: "image/p9.jpg",
    cat: "laptop",
    type: "new",
  },
  {
    id: 5,
    Name: "product5",
    price: "98",
    image: "image/p4.webp",
    cat: "speaker",
    type: "featured",
  },
  {
    id: 6,
    Name: "product6",
    price: "59",
    image: "image/p5.webp",
    cat: "electronics",
    type: "featured",
  },
  {
    id: 7,
    Name: "product7",
    price: "956",
    image: "image/p10.jpg",
    cat: "headphone",
    type: "featured",
  },
  {
    id: 8,
    Name: "product8",
    price: "389",
    image: "image/p11.jpg",
    cat: "electronics",
    type: "featured",
  },
  {
    id: 9,
    Name: "product9",
    price: "67",
    image: "image/p6.webp",
    cat: "phone",
    type: "top",
  },
  {
    id: 10,
    Name: "product10",
    price: "76",
    image: "image/p7.webp",
    cat: "speaker",
    type: "top",
  },
  {
    id: 11,
    Name: "product11",
    price: "87",
    image: "image/p8.webp",
    cat: "speaker",
    type: "top",
  },
  {
    id: 12,
    Name: "product12",
    price: "807",
    image: "image/p12.jpg",
    cat: "speaker",
    type: "top",
  },
];
export default Homeproduct;
